export { default as FeaturesSection } from './Features';
export { default as TestimonialsSection } from './Testimonials';
export { default as ProductColorsSection } from './ProductColors';
export { default as HeroSection } from './Hero';
export { default as ProductInfoSection } from './ProductInfo';
export { default as HighEfficiencySection } from './HighEfficiency';
export { default as MultipleAccessoriesSection } from './MultipleAccessories';
export { default as GallerySection } from './Gallery';
export { default as NewsletterSection } from './Newsletter';
